app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/', function () {
    return Redirect::to('/admins');
});

Route::get('login', array('as' => 'sessions.login', 'uses' => 'SessionsController@showLogin'));
Route::post('login', array('as' => 'sessions.login', 'uses' => 'SessionsController@processLogin'));

Route::resource('admins', 'AdminsController');

Route::resource('campaigns', 'CampaignsController');

Route::resource('dashboards', 'DashboardsController');

Route::resource('emails', 'EmailsController');

Route::resource('roles', 'RolesController');

Route::resource('subscribers', 'SubscribersController');

Route::resource('subscriptions', 'SubscriptionsController');

Route::resource('users', 'UsersController');

Route::resource('teams', 'TeamsController');

Route::get('contacts/import', array('as' => 'contacts.import', 'uses' => 'ContactsController@getImport'));
Route::post('contacts/import', array('as' => 'contacts.import', 'uses' => 'ContactsController@postImport'));
Route::resource('contacts', 'ContactsController');


Route::resource('mailing_lists', 'MailingListsController');

app/views/admins/create.blade.php
@extends('layouts.scaffold')

@section('main')

<h1>Create Admin</h1>

@if ($errors->any())
    <ul>
        {{ implode('', $errors->all('<li class="error">:message</li>')) }}
    </ul>
@endif

{{ Form::open(array('route' => 'admins.store')) }}
    <ul>
        
        @include('admins.form')

        <li>
            {{ Form::submit('Submit', array('class' => 'btn btn-info')) }}
        </li>
    </ul>
{{ Form::close() }}

@stop

app/views/admins/index.blade.php
@extends('layouts.master')


@section('nav')

    @parent
    <!-- <p> appended to master sidebar</p> -->

@stop


@section('main')

<style>
    @import url(https://fonts.googleapis.com/css?family=Lato:300,400,700);
    body {
        -webkit-background-size: cover;
        -moz-background-size: cover;
        -o-background-size: cover;
        background-size: cover;
        font-family: 'Lato';
    }
    button {
        border-radius: 0 0 4px 4px !important;
        
    }
    .package {
        background-color: #B2CCFF;
        
        border-radius: 4px;
        text-align: center;
        padding: 10px;
        margin: 0 0 20px;
        height: 155px;
        position: relative;
    }
    .package .title,
    .package .count {
        display: table;
        height: 50%;
        width: 100%;
    }
    h1 {
        display: table-cell;
        vertical-align: middle;
        font-family: 'Lato';
        font-weight: 300;
        font-size:24px;
        color: #333;
        margin-bottom: 10px;
    }
    h2 {
        display: table-cell;
        vertical-align: top;
        font-family: 'Lato';
        font-weight: 400;
        font-size: 60px;
        color: #666;
        margin: 0 0;
        line-height: 55px;
    }
    .row {margin:0 0;position: relative;}
    .row > .row {
        margin-left: -15px;
        margin-right:-15px;
    }
</style>



    <div class="page-header">
      <h1>Admin
      </br><small>Manage</small></h1>
    </div>
    

    
    <div class="row" style="padding:0px 50px;margin-top:50px;">
        <div class="row">
            <div class="col-md-3 ">
                <a href="{{ URL::to('users') }}">
                    <div class="package">
                        <div class="title"><h1>Users</h1></div>
                        <div class="count"><h2><i class="fa fa-user"></i></h2></div>
                    </div>
                </a>
            </div>
            <div class="col-md-3 ">
                <a href="{{ URL::to('teams') }}">
                    <div class="package">
                        <div class="title"><h1>Teams</h1></div>
                        <div class="count"><h2><i class="fa fa-users"></i></h2></div>
                    </div>
                </a>
            </div>
            <div class="col-md-3 ">
                <a href="{{ URL::to('roles') }}">
                    <div class="package">
                        <div class="title"><h1>Roles</h1></div>
                        <div class="count"><h2><i class="fa fa-sitemap"></i></h2></div>
                    </div>
                </a>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>


@stop

app/views/admins/show.blade.php
@extends('layouts.scaffold')

@section('main')

<h1>Show Admin</h1>

<p>{{ link_to_route('admins.index', 'Return to all admins') }}</p>

<table class="table table-striped table-bordered">
    <thead>
        <tr>
        </tr>
    </thead>

    <tbody>
        <tr>

            <td>{{ link_to_route('admins.edit', 'Edit', array($admin->id), array('class' => 'btn btn-info')) }}</td>
            <td>
                {{ Form::open(array('method' => 'DELETE', 'route' => array('admins.destroy', $admin->id))) }}
                    {{ Form::submit('Delete', array('class' => 'btn btn-danger')) }}
                {{ Form::close() }}
            </td>
        </tr>
    </tbody>
</table>

@stop

app/views/admins/update.blade.php
@extends('layouts.scaffold')

@section('main')

<h1>Edit Admin</h1>

@if ($errors->any())
    <ul>
        {{ implode('', $errors->all('<li class="error">:message</li>')) }}
    </ul>
@endif

{{ Form::model($admin, array('method' => 'PATCH', 'route' => array('admins.update', $admin->id))) }}
    <ul>
        
        @include('admins.form')

        <li>
            {{ Form::submit('Update', array('class' => 'btn btn-info')) }}
            {{ link_to_route('admins.show', 'Cancel', $admin->id, array('class' => 'btn')) }}
        </li>

    </ul>
{{ Form::close() }}

@stop