app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/', function () {
    return Redirect::to('/admins');
});

Route::get('login', array('as' => 'sessions.login', 'uses' => 'SessionsController@showLogin'));
Route::post('login', array('as' => 'sessions.login', 'uses' => 'SessionsController@processLogin'));

Route::resource('admins', 'AdminsController');

Route::resource('campaigns', 'CampaignsController');

Route::resource('dashboards', 'DashboardsController');

Route::resource('emails', 'EmailsController');

Route::resource('roles', 'RolesController');

Route::resource('subscribers', 'SubscribersController');

Route::resource('subscriptions', 'SubscriptionsController');

Route::resource('users', 'UsersController');

Route::resource('teams', 'TeamsController');

Route::get('contacts/import', array('as' => 'contacts.import', 'uses' => 'ContactsController@getImport'));
Route::post('contacts/import', array('as' => 'contacts.import', 'uses' => 'ContactsController@postImport'));
Route::resource('contacts', 'ContactsController');


Route::resource('mailing_lists', 'MailingListsController');

app/views/mailing_list_filters/create.blade.php
@extends('layouts.master')

@section('main')

<h1>Create Mailing List</h1>

@if ($errors->any())
    <ul>
        {{ implode('', $errors->all('<li class="error">:message</li>')) }}
    </ul>
@endif

{{ Form::open(array('route' => 'mailing_lists.store')) }}
    <ul>
        
        @include('mailing_lists.form')
        @include('mailing_list_filters.form')

        <li>
            {{ Form::submit('Submit', array('class' => 'btn btn-info')) }}
        </li>
    </ul>
{{ Form::close() }}

@stop

app/views/mailing_list_filters/form.blade.php
<div class="row">
    <div class="form-group">
        {{ Form::label('operator_column', 'Select contacts whose', array('class'=> 'col-sm-2 control-label')) }}
        <div class='col-sm-2'>
            {{ Form::select('operator_column', array(
                'default' => '',
                'age' => 'age', 
                'gender' => 'gender'
            ), null, array('class'=> 'form-control')) }}
        </div>

        {{ Form::label('operator', ' ', array('class' => 'col-sm-0 control-label')) }}
        <div class='col-sm-3'>
            {{ Form::select('operator', array(
                'default' => '',
                '=' => 'is equal to',
                '>' => 'is greater than',
                '>=' => 'is greater than or equal to',
                '<' => 'is less than',
                '<=' => 'is less than or equal to',
                'BETWEEN' => 'is between'
            ), null, array('class'=> 'form-control')) }}
        </div>

        
        <?php $age_list = array('default' => '');
        foreach (range(1, 100) as $number) {
            $age_list[$number] = $number;
        }
        ?>

        {{ Form::label('column_value', ' ', array('class' => 'col-sm-0 control-label')) }}
        <div class='col-sm-2'>
            {{ Form::select('column_value', $age_list, null, array('class'=> 'form-control')) }}
        </div>
    </div>
</div>

app/views/mailing_list_filters/index.blade.php
@extends('layouts.master')

@section('main')

<h1>All MailingLists</h1>

<p>{{ link_to_route('mailing_lists.create', 'Add new ') }}</p>

@if ($mailing_lists->count())
    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th>id</th>
                <th>user_id</th>
                <th>operator_name</th>
                <th>operator</th>
                <th>operator_value</th>
            </tr>
        </thead>

        <tbody>
            @foreach ($mailing_lists as $mailing_list)
                <tr>
                    <td>{{ $mailing_list->id }}</td>
                    <td>{{ $mailing_list->user_id }}</td>
                    <td>{{ $mailing_list->operator_name }}</td>
                    <td>{{ $mailing_list->operator }}</td>
                    <td>{{ $mailing_list->operator_value }}</td>

                    <td>{{ link_to_route('mailing_lists.show', 'View', array($mailing_list->id), array('class' => 'btn')) }}</td>

                    <td>{{ link_to_route('mailing_lists.edit', 'Edit', array($mailing_list->id), array('class' => 'btn btn-info')) }}</td>

                    <td>
                        {{ Form::open(array('method' => 'DELETE', 'route' => array('mailing_lists.destroy', $mailing_list->id))) }}
                            {{ Form::submit('Delete', array('class' => 'btn btn-danger')) }}
                        {{ Form::close() }}
                    </td>

                </tr>
            @endforeach
        </tbody>
    </table>
@else
    There are no mailing_lists
@endif

@stop

app/views/mailing_list_filters/show.blade.php
@extends('layouts.scaffold')

@section('main')

<h1>Show MailingList</h1>

<p>{{ link_to_route('mailing_lists.index', 'Return to all mailing_lists') }}</p>

<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>id</th>
            <th>user_id</th>
            <th>operator_name</th>
            <th>operator</th>
            <th>operator_value</th>
        </tr>
    </thead>

    <tbody>
        <tr>
            <td>{{ $mailing_list->id }}</td>
            <td>{{ $mailing_list->user_id }}</td>
            <td>{{ $mailing_list->operator_name }}</td>
            <td>{{ $mailing_list->operator }}</td>
            <td>{{ $mailing_list->operator_value }}</td>

            <td>{{ link_to_route('mailing_lists.edit', 'Edit', array($mailing_list->id), array('class' => 'btn btn-info')) }}</td>
            <td>
                {{ Form::open(array('method' => 'DELETE', 'route' => array('mailing_lists.destroy', $mailing_list->id))) }}
                    {{ Form::submit('Delete', array('class' => 'btn btn-danger')) }}
                {{ Form::close() }}
            </td>
        </tr>
    </tbody>
</table>

@stop

app/views/mailing_list_filters/update.blade.php
@extends('layouts.scaffold')

@section('main')

<h1>Edit MailingList</h1>

@if ($errors->any())
    <ul>
        {{ implode('', $errors->all('<li class="error">:message</li>')) }}
    </ul>
@endif

{{ Form::model($mailing_list, array('method' => 'PATCH', 'route' => array('mailing_lists.update', $mailing_list->id))) }}
    <ul>
        
        @include('mailing_lists.form')

        <li>
            {{ Form::submit('Update', array('class' => 'btn btn-info')) }}
            {{ link_to_route('mailing_lists.show', 'Cancel', $mailing_list->id, array('class' => 'btn')) }}
        </li>

    </ul>
{{ Form::close() }}

@stop