app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/', function () {
    return Redirect::to('/admins');
});

Route::get('login', array('as' => 'sessions.login', 'uses' => 'SessionsController@showLogin'));
Route::post('login', array('as' => 'sessions.login', 'uses' => 'SessionsController@processLogin'));

Route::resource('admins', 'AdminsController');

Route::resource('campaigns', 'CampaignsController');

Route::resource('dashboards', 'DashboardsController');

Route::resource('emails', 'EmailsController');

Route::resource('roles', 'RolesController');

Route::resource('subscribers', 'SubscribersController');

Route::resource('subscriptions', 'SubscriptionsController');

Route::resource('users', 'UsersController');

Route::resource('teams', 'TeamsController');

Route::get('contacts/import', array('as' => 'contacts.import', 'uses' => 'ContactsController@getImport'));
Route::post('contacts/import', array('as' => 'contacts.import', 'uses' => 'ContactsController@postImport'));
Route::resource('contacts', 'ContactsController');


Route::resource('mailing_lists', 'MailingListsController');

app/models/Contact.php
<?php

namespace Mail;

use Contracts\Instances\InstanceInterface;
use Illuminate\Database\Eloquent\Model as Eloquent;

class Contact extends Eloquent implements InstanceInterface
{
    protected $guarded = [];

    public function identity()
    {
        return $this->id;
    }

    public function subscriptions()
    {
        return $this->belongsToMany('Mail\Subscription', 'contacts_subscriptions');
    }
}

app/controllers/ContactsController.php
<?php

use Services\ContactCreator;
use Contracts\Repositories\ContactRepositoryInterface;
use Contracts\Repositories\SubscriptionRepositoryInterface;
use Contracts\Instances\InstanceInterface;
use Contracts\Notification\CreatorInterface;
use Contracts\Notification\UpdaterInterface;
use Contracts\Notification\DestroyerInterface;
use Validators\Validator as Validator;

class ContactsController extends BaseController implements CreatorInterface, UpdaterInterface, DestroyerInterface
{

    /**
     * Contact Repository
     *
     * @var ContactRepositoryInterface
     */
    protected $contact;

    public function __construct(
        ContactRepositoryInterface $contact,
        SubscriptionRepositoryInterface $subscription
    ) {
        $this->contact = $contact;
        $this->subscription = $subscription;
    }

    /**
     * Display a listing of the contacts.
     *
     * @return Response
     */
    public function index()
    {
        $contacts = $this->contact->all();

        return View::make('contacts.index', compact('contacts'));
    }

    /**
     * Show the form for creating a new contact.
     *
     * @return Response
     */
    public function create()
    {
        return View::make('contacts.create');
    }

    /**
     * Store a newly created contact in storage.
     *
     * @return Response
     */
    public function store()
    {
        $contact_creator = App::make('Services\Contacts\ContactCreator');

        return $contact_creator->create($this->contact, $this, Input::except('_token'));
    }

    /**
     * Handle successful contact creation
     *
     * @param  InstanceInterface $instance
     * @return Redirect::route
     */
    public function creationSucceeded(InstanceInterface $instance)
    {
        return Redirect::route('contacts.index')->with('message', 'Contact was successfully created');
    }

    /**
     * Handle an error with contact creation
     *
     * @param  Validator\Validator      $validator
     * @return Redirect::route
     */
    public function creationFailed(Validator $validator)
    {
        return Redirect::route('contacts.create')
            ->withInput()
            ->withErrors($validator->errors())
            ->with('message', 'Oops, there was an error');
    }

    /**
     * Display the specified contact.
     *
     * @param  int      $id
     * @return Response
     */
    public function show($id)
    {
        $contact = $this->contact->getByIdWithSubscriptionNames($id);

        return View::make('contacts.show', compact('contact'));
    }

    /**
     * Show the form for editing the specified contact.
     *
     * @param  int      $id
     * @return Response
     */
    public function edit($id)
    {
        $contact = $this->contact->getByIdWithSubscriptionIds($id);
        $subscriptions = $this->subscription->all();

        return View::make('contacts.edit', compact('contact', 'subscriptions'));
    }

    /**
     * Update the specified contact in storage.
     *
     * @param  int      $id
     * @return Response
     */
    public function update($id)
    {
        $contact_updater = App::make('Services\Contacts\ContactUpdater');

        return $contact_updater->update($this->contact, $this, $id, Input::except('_method'));
    }

    /**
     * Handle successful contact update
     *
     * @param  InstanceInterface $instance
     * @return Redirect::route
     */
    public function updateSucceeded(InstanceInterface $instance)
    {
        return Redirect::route('contacts.show', $instance->identity());
    }

    /**
     * Handle an error with contact update
     *
     * @param  InstanceInterface $instance
     * @param  Validator\Validator      $validator
     * @return Redirect::route
     */
    public function updateFailed(InstanceInterface $instance, Validator $validator)
    {
        return Redirect::route('contacts.edit', $instance->identity())
            ->withInput()
            ->withErrors($validator->errors())
            ->with('message', 'Oops, there was an error');
    }

    /**
     * Remove the specified contact from storage.
     *
     * @param  int      $id
     * @return Response
     */
    public function destroy($id)
    {
        $contact_destroyer = App::make('Services\Contacts\ContactDestroyer');

        return $contact_destroyer->destroy($this->contact, $this, $id, Input::except('_method'));
    }

    /**
     * Handle successful contact destroy
     *
     * @param  InstanceInterface $instance
     * @return Redirect::route
     */
    public function destroySucceeded(InstanceInterface $instance)
    {
        return Redirect::route('contacts.index')->with('message', 'Contact was successfully deleted');
    }

    /**
     * Handle an error with contact destroy
     *
     * @param  InstanceInterface $instance
     * @return Redirect::route
     */
    public function destroyFailed(InstanceInterface $instance)
    {
        return Redirect::route('contacts.index')->with('message', 'Oops, couldn\'t delete that contact');
    }

    public function getImport()
    {
        return 'test';
    }
}

app/views/contacts/create.blade.php
@extends('layouts.master')

@section('main')

<h1>Create Contact</h1>

@if ($errors->any())
    <ul>
        {{ implode('', $errors->all('<li class="error">:message</li>')) }}
    </ul>
@endif

{{ Form::open(array('route' => 'contacts.store')) }}
    
        
        @include('contacts.form')

        
            {{ Form::submit('Submit', array('class' => 'btn btn-info')) }}
        
{{ Form::close() }}

@stop

app/views/contacts/edit.blade.php
@extends('layouts.master')

@section('main')

<h1>Edit {{{ $contact->email }}}</h1>

@if ($errors->any())
    <ul>
        {{ implode('', $errors->all('<li class="error">:message</li>')) }}
    </ul>
@endif

{{ Form::model($contact, array(
    'method' => 'PATCH',
    'class' => 'form-horizontal',
    'role' => 'form',
    'route' => array('contacts.update', $contact->id))) }}
    
        
        @include('contacts.form')

        <div class="col-xs-12 col-md-6 well">
                {{ Form::button(null, array('class' => 'btn btn-success')).' = Subscribe'}}
                {{ Form::button(null, array('class' => 'btn btn-danger')).' = Unsubscribe'}}
                </br>

                @foreach ($subscriptions as $subscription)
                    @if (in_array($subscription->id, $contact->subscriptions))
                        {{ Form::button($subscription->name, array('class' => 'btn btn-success')) }}
                    @else
                        {{ Form::button($subscription->name, array('class' => 'btn btn-danger')) }}
                    @endif

                    </br>
                @endforeach

                </br>
                </br>

                
            </div>

        
            {{ Form::submit('Update', array('class' => 'btn btn-info')) }}
            {{ link_to_route('contacts.show', 'Cancel', $contact->id, array('class' => 'btn')) }}
        

    
{{ Form::close() }}

@stop

app/views/contacts/form.blade.php
<div class="row">
    <div class="col-xs-12 col-md-10 well">
        <div class="form-group">
            {{ Form::label('email', 'Email', array('class'=> 'col-sm-2 control-label')) }}
            <div class='col-sm-4'>
                {{ Form::email('email', null, array('class'=> 'form-control')) }}
            </div>
        </div>

        <div class="form-group">
            {{ Form::label('first_name', 'First Name', array('class' => 'col-sm-2 control-label')) }}
            <div class='col-sm-4'>
                {{ Form::text('first_name', null, array('class'=> 'form-control')) }}
            </div>
            
            {{ Form::label('last_name', 'Last Name', array('class' => 'col-sm-2 control-label')) }}
            <div class='col-sm-4'>
                {{ Form::text('last_name', null, array('class'=> 'form-control')) }}
            </div>
        </div>

        </br>
        </br>
        </br>

        <div class="form-group">
            {{ Form::label('address', 'Address', array('class' => 'col-sm-2 control-label')) }}
            <div class='col-sm-4'>
                {{ Form::text('address', null, array('class'=> 'form-control')) }}
            </div>
        </div>

        <div class="form-group">
            {{ Form::label('secondary_address', 'Address 2', array('class' => 'col-sm-2 control-label')) }}
            <div class='col-sm-4'>
                {{ Form::text('secondary_address', null, array('class'=> 'form-control')) }}
            </div>
        </div>

        <div class="form-group">
            {{ Form::label('city', 'City', array('class' => 'col-sm-2 control-label')) }}
            <div class='col-sm-4'>
                {{ Form::text('city', null, array('class'=> 'form-control')) }}
            </div>

            {{ Form::label('state', 'State', array('class' => 'col-sm-2 control-label')) }}
            <div class='col-sm-4'>
                {{ Form::select('state', array(
                    'AL'=>'Alabama',
                    'AK'=>'Alaska',
                    'AZ'=>'Arizona',
                    'AR'=>'Arkansas',
                    'CA'=>'California',
                    'CO'=>'Colorado',
                    'CT'=>'Connecticut',
                    'DE'=>'Delaware',
                    'DC'=>'District of Columbia',
                    'FL'=>'Florida',
                    'GA'=>'Georgia',
                    'HI'=>'Hawaii',
                    'ID'=>'Idaho',
                    'IL'=>'Illinois',
                    'IN'=>'Indiana',
                    'IA'=>'Iowa',
                    'KS'=>'Kansas',
                    'KY'=>'Kentucky',
                    'LA'=>'Louisiana',
                    'ME'=>'Maine',
                    'MD'=>'Maryland',
                    'MA'=>'Massachusetts',
                    'MI'=>'Michigan',
                    'MN'=>'Minnesota',
                    'MS'=>'Mississippi',
                    'MO'=>'Missouri',
                    'MT'=>'Montana',
                    'NE'=>'Nebraska',
                    'NV'=>'Nevada',
                    'NH'=>'New Hampshire',
                    'NJ'=>'New Jersey',
                    'NM'=>'New Mexico',
                    'NY'=>'New York',
                    'NC'=>'North Carolina',
                    'ND'=>'North Dakota',
                    'OH'=>'Ohio',
                    'OK'=>'Oklahoma',
                    'OR'=>'Oregon',
                    'PA'=>'Pennsylvania',
                    'RI'=>'Rhode Island',
                    'SC'=>'South Carolina',
                    'SD'=>'South Dakota',
                    'TN'=>'Tennessee',
                    'TX'=>'Texas',
                    'UT'=>'Utah',
                    'VT'=>'Vermont',
                    'VA'=>'Virginia',
                    'WA'=>'Washington',
                    'WV'=>'West Virginia',
                    'WI'=>'Wisconsin',
                    'WY'=>'Wyoming',
                    'ZZ' => 'Other'
                ), null, array('class'=> 'form-control')) }}
            </div>
        </div>

        <div class="form-group">
            {{ Form::label('zip', 'Zip', array('class' => 'col-sm-2 control-label')) }}
            <div class='col-sm-4'>
                {{ Form::text('zip', null, array('class'=> 'form-control')) }}
            </div>

            {{ Form::label('country', 'Country', array('class' => 'col-sm-2 control-label')) }}
            <div class='col-sm-4'>
                {{ Form::text('country', null, array('class'=> 'form-control')) }}
            </div>
        </div>
    

        <div class="form-group">
            {{ Form::label('gender', 'Gender', array('class' => 'col-sm-2 control-label')) }}
            <div class='col-sm-4'>
                {{ Form::select('gender', array(
                    'F' => 'Female',
                    'M' => 'Male'
                ), null, array('class'=> 'form-control')) }}
            </div>
        </div>

        <div class="form-group">
            {{ Form::label('shirt_size', 'Shirt Size', array('class' => 'col-sm-2 control-label')) }}
            <div class='col-sm-4'>
                {{ Form::select('shirt_size', array(
                    'XS' => 'X-Small', 
                    'S' => 'Small', 
                    'M' => 'Medium', 
                    'L' => 'Large',
                    'XL' => 'X-Large'
                ), null, array('class'=> 'form-control')) }}
            </div>
        </div>

        <div class="form-group">
            {{ Form::label('birthdate', 'Birthdate', array('class' => 'col-sm-2 control-label')) }}
            <div class='col-sm-4'>
                {{ Form::text('birthdate', null, array('class'=> 'form-control')) }}
            </div>
        </div>

        <div class="form-group">
            {{ Form::label('phone', 'Phone Number', array('class' => 'col-sm-2 control-label')) }}
            <div class='col-sm-4'>
                {{ Form::text('phone', null, array('class'=> 'form-control')) }}
            </div>
        </div>
    </div>
</div>

app/views/contacts/index.blade.php
@extends('layouts.master')

@section('main')

    <div class="page-header">
      <h1>My Contacts <small>Subheader</small></h1>
    </div>
    <div class="row">
        <div class="pull-left">
            <p>{{ link_to_route('contacts.create', 'Add new ') }}</p>
        </div>
        <div class="pull-right">
            <p>{{ link_to_route('contacts.import', 'Create new contacts from file (.csv)') }}</p>
            <p>{{ link_to_route('contacts.update', 'Update existing contacts using file (.csv)') }}</p>
            <p>{{ link_to_route('contacts.destroy', 'Remove existing contacts using file (.csv)') }}</p>
        </div>
    </div>
    @if ($contacts->count())

        <table class="table table-condensed table-hover table-bordered">
            <tr>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Email</th>
            </tr>

            @foreach ($contacts as $contact)
                <tr>
                    <td>{{ link_to_route('contacts.show', $contact->first_name, array($contact->id), array('class' => 'btn')) }}</td>
                    <td>{{{ $contact->last_name }}}</td>
                    <td>{{{ $contact->email }}}</td>
                    
                </tr>
            @endforeach
        </table>

    @else
        There are no contacts. Create them by blah blah blah
    @endif

@stop

app/views/contacts/show.blade.php
@extends('layouts.master')

@section('main')

    <div class="page-header">
        <h1>{{{ $contact->first_name }}} {{{ $contact->last_name }}}
            </br>
            <small>Manage Your Profile</small>
        </h1>
    </div>

<p>{{ link_to_route('contacts.index', 'Return to all contacts') }}</p>

        <div class="row">
            <div class="col-xs-12 col-md-6 well">

                <div>
                    {{{ $contact->first_name }}} {{{ $contact->last_name }}}
                </div>

                <div>
                    {{{ $contact->email }}}
                </div>

                <div>
                    {{{ $contact->address }}}
                </div>

                <div>
                    {{{ $contact->secondary_address }}}
                </div>

                <div>
                    {{{ $contact->city }}}, {{{ $contact->state }}} {{{ $contact->zip }}}
                </div>

                <div>
                    {{{ $contact->country }}}
                </div>
            

                <div>
                    Gender: {{{ $contact->gender }}}
                </div>

                <div>
                    Shirt Size: {{{ $contact->shirt_size }}}
                </div>

                <div>
                    Birthdate: {{{ $contact->birthdate }}}
                </div>

                <div>
                    Phone: {{{ $contact->phone }}}
                </div>
            </div>

            @foreach ($contact->subscriptions as $subscription)
                {{ Form::button($subscription->name, array('class' => 'btn btn-success')) }}
                    </br>
                @endforeach
                

            
        </div>

<table class="table table-striped table-bordered">
    <thead>
        <tr>
        </tr>
    </thead>

    <tbody>
        <tr>

            <td>{{ link_to_route('contacts.edit', 'Edit', array($contact->id), array('class' => 'btn btn-info')) }}</td>
            <td>
                {{ Form::open(array('method' => 'DELETE', 'route' => array('contacts.destroy', $contact->id))) }}
                    {{ Form::submit('Delete', array('class' => 'btn btn-danger')) }}
                {{ Form::close() }}
            </td>
        </tr>
    </tbody>
</table>

@stop

app/views/contacts/update.blade.php
@extends('layouts.master')

@section('main')

<h1>Edit Contact</h1>

@if ($errors->any())
    <ul>
        {{ implode('', $errors->all('<li class="error">:message</li>')) }}
    </ul>
@endif

{{ Form::model($contact, array('method' => 'PATCH', 'route' => array('contacts.update', $contact->id))) }}
    <ul>
        
        @include('contacts.form')

        <li>
            {{ Form::submit('Update', array('class' => 'btn btn-info')) }}
            {{ link_to_route('contacts.show', 'Cancel', $contact->id, array('class' => 'btn')) }}
        </li>

    </ul>
{{ Form::close() }}

@stop